// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Grid lays out children in a CSS grid with optional column wrappers.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { gridClasses, gridColClasses } from "./grid.shared";

/**
 * Grid renders a display:grid container.
 */
export type GridProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children" | "cols"> & {
  cols?: string;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Grid: Component<GridProps> = (props) => {
  const [local, rest] = splitProps(props, ["cols", "class", "className", "children"]);
  const cls = () => gridClasses({ cols: local.cols, className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} {...rest}>
      {local.children}
    </div>
  );
};

/**
 * GridCol renders one grid column child.
 */
export type GridColProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children" | "span" | "start" | "end" | "order"> & {
  span?: number;
  start?: number;
  end?: number;
  order?: number;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const GridCol: Component<GridColProps> = (props) => {
  const [local, rest] = splitProps(props, ["span", "start", "end", "order", "class", "className", "children"]);
  const cls = () => gridColClasses({ span: local.span, start: local.start, end: local.end, order: local.order, className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} {...rest}>
      {local.children}
    </div>
  );
};
