// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Group arranges children in a horizontal flex row.
 * Supports fieldset for related form controls.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { groupClasses } from "./group.shared";
import { resolveTag, TagGroup } from "../../utils/tags";

/**
 * Group renders a horizontal flex container.
 */
export type GroupProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "tag"> & {
  tag?: string;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Group: Component<GroupProps> = (props) => {
  const [local, rest] = splitProps(props, ["tag", "class", "className", "children"]);
  const resolvedTagValue = () => resolveTag(local.tag, "div", TagGroup.Group);
  const cls = () => groupClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};
