// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Switch is a toggle control (checkbox with switch ARIA semantics).
 * Use for on/off settings; wireframe uses native checkbox styling.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { switchClasses, type SwitchSize, type SwitchVariant } from "./switch.shared";
import { boolStr } from "../../utils/expr";

/**
 * Switch renders input[type=checkbox] with switch role attrs.
 */
export type SwitchProps = Omit<JSX.InputHTMLAttributes<HTMLInputElement>, "class" | "className" | "children" | "variant" | "size" | "checked" | "disabled" | "required"> & {
  variant?: SwitchVariant;
  size?: SwitchSize;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
  class?: string;
  className?: string;
};

export const Switch: Component<SwitchProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "checked", "disabled", "required", "class", "className"]);
  const cls = () => switchClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <input type="checkbox" class={cls() || undefined} checked={local.checked || undefined} disabled={local.disabled || undefined} required={local.required || undefined} role="switch" aria-checked={boolStr(local.checked)} {...rest} />
  );
};
