// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Radio is a native single-choice control within a named group.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { radioClasses, type RadioSize, type RadioVariant } from "./radio.shared";

/**
 * Radio renders input[type=radio] with shared Name for grouping.
 */
export type RadioProps = Omit<JSX.InputHTMLAttributes<HTMLInputElement>, "class" | "className" | "children" | "variant" | "size" | "checked" | "disabled" | "required"> & {
  variant?: RadioVariant;
  size?: RadioSize;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
  class?: string;
  className?: string;
};

export const Radio: Component<RadioProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "checked", "disabled", "required", "class", "className"]);
  const cls = () => radioClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <input type="radio" class={cls() || undefined} checked={local.checked || undefined} disabled={local.disabled || undefined} required={local.required || undefined} {...rest} />
  );
};
