// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Alert displays a static status or informational message.
 * Renders a live region with role=status by default; children carry the message body.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { alertClasses, type AlertVariant } from "./alert.shared";
import { defaultIfEmpty, oneOfOr } from "../../utils/expr";

/**
 * Alert renders a div with alert or status semantics.
 */
export type AlertProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children" | "variant" | "role" | "aria-live"> & {
  variant?: AlertVariant;
  role?: "status" | "alert";
  "aria-live"?: "off" | "polite" | "assertive";
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Alert: Component<AlertProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "role", "aria-live", "class", "className", "children"]);
  const cls = () => alertClasses({ variant: local.variant, className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} role={oneOfOr(local.role, "status", "status", "alert")} aria-live={defaultIfEmpty(local["aria-live"], "polite")} {...rest}>
      {local.children}
    </div>
  );
};
