// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Select is a native dropdown built from Option items.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { optGroupClasses, selectClasses, type SelectOptionItem, type SelectSize, type SelectVariant } from "./select.shared";
import { eqStr } from "../../utils/expr";

/**
 * Select renders option children from the Options list plus manual children.
 */
export type SelectProps = Omit<JSX.SelectHTMLAttributes<HTMLSelectElement>, "class" | "className" | "children" | "variant" | "size" | "value" | "disabled" | "required" | "options"> & {
  variant?: SelectVariant;
  size?: SelectSize;
  value?: string;
  disabled?: boolean;
  required?: boolean;
  options?: SelectOptionItem[];
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Select: Component<SelectProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "value", "disabled", "required", "options", "class", "className", "children"]);
  const cls = () => selectClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <select class={cls() || undefined} disabled={local.disabled || undefined} required={local.required || undefined} {...rest}>
      {(local.options ?? []).map((item, index) => (
        <option value={(item.value) ?? ""} selected={eqStr(item.value, local.value) || undefined}>
          {item.label}
        </option>
      ))}
      {local.children}
    </select>
  );
};

/**
 * SelectOption renders an option for custom Select children.
 */
export type SelectOptionProps = Omit<JSX.OptionHTMLAttributes<HTMLOptionElement>, "class" | "className" | "children" | "selected" | "disabled"> & {
  selected?: boolean;
  disabled?: boolean;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const SelectOption: Component<SelectOptionProps> = (props) => {
  const [local, rest] = splitProps(props, ["selected", "disabled", "class", "className", "children"]);
  return (
    <option selected={local.selected || undefined} disabled={local.disabled || undefined} {...rest}>
      {local.children}
    </option>
  );
};

/**
 * OptGroup renders a native optgroup around option children.
 */
export type OptGroupProps = Omit<JSX.OptgroupHTMLAttributes<HTMLOptGroupElement>, "class" | "className" | "children" | "disabled"> & {
  disabled?: boolean;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const OptGroup: Component<OptGroupProps> = (props) => {
  const [local, rest] = splitProps(props, ["disabled", "class", "className", "children"]);
  const cls = () => optGroupClasses({ className: local.class ?? local.className });
  return (
    <optgroup class={cls() || undefined} disabled={local.disabled || undefined} {...rest}>
      {local.children}
    </optgroup>
  );
};
