// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Card groups related content in one bordered surface.
 * Card uses header, content, and footer slots.
 * For semantic root elements (section, article), use CardClasses on a manual wrapper.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { cardClasses, cardContentClasses, cardDescriptionClasses, cardFooterClasses, cardHeaderClasses, cardTitleClasses, type CardVariant } from "./card.shared";
import { titleTag } from "../../utils/expr";

/**
 * Card renders the bordered surface wrapper.
 */
export type CardProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children" | "variant"> & {
  variant?: CardVariant;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Card: Component<CardProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "class", "className", "children"]);
  const cls = () => cardClasses({ variant: local.variant, className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} {...rest}>
      {local.children}
    </div>
  );
};

/**
 * CardHeader renders the top slot.
 */
export type CardHeaderProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const CardHeader: Component<CardHeaderProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className", "children"]);
  const cls = () => cardHeaderClasses({ className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} {...rest}>
      {local.children}
    </div>
  );
};

/**
 * CardTitle renders heading text at the As level (default h2).
 */
export type CardTitleProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "as"> & {
  as?: 1 | 2 | 3 | 4 | 5 | 6;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const CardTitle: Component<CardTitleProps> = (props) => {
  const [local, rest] = splitProps(props, ["as", "class", "className", "children"]);
  const resolvedTagValue = () => titleTag(local.as);
  const cls = () => cardTitleClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};

/**
 * CardDescription renders a muted subtitle in a p element.
 */
export type CardDescriptionProps = Omit<JSX.HTMLAttributes<HTMLParagraphElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const CardDescription: Component<CardDescriptionProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className", "children"]);
  const cls = () => cardDescriptionClasses({ className: local.class ?? local.className });
  return (
    <p class={cls() || undefined} {...rest}>
      {local.children}
    </p>
  );
};

/**
 * CardContent renders the padded main body slot.
 */
export type CardContentProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const CardContent: Component<CardContentProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className", "children"]);
  const cls = () => cardContentClasses({ className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} {...rest}>
      {local.children}
    </div>
  );
};

/**
 * CardFooter renders the bottom action slot.
 */
export type CardFooterProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const CardFooter: Component<CardFooterProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className", "children"]);
  const cls = () => cardFooterClasses({ className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} {...rest}>
      {local.children}
    </div>
  );
};
