// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Checkbox is a native boolean form control.
 * Wireframe styling via Variant and Size; supports standard ARIA attrs.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { checkboxClasses, type CheckboxSize, type CheckboxVariant } from "./checkbox.shared";

/**
 * Checkbox renders a styled input[type=checkbox].
 */
export type CheckboxProps = Omit<JSX.InputHTMLAttributes<HTMLInputElement>, "class" | "className" | "children" | "variant" | "size" | "checked" | "disabled" | "required"> & {
  variant?: CheckboxVariant;
  size?: CheckboxSize;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
  class?: string;
  className?: string;
};

export const Checkbox: Component<CheckboxProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "checked", "disabled", "required", "class", "className"]);
  const cls = () => checkboxClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <input type="checkbox" class={cls() || undefined} checked={local.checked || undefined} disabled={local.disabled || undefined} required={local.required || undefined} {...rest} />
  );
};
