// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Break renders br or wbr for controlled inline wrapping.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { breakClasses } from "./linebreak.shared";
import { mapOr } from "../../utils/expr";

/**
 * Break renders br by default, or wbr when Type is wbr/word.
 */
export type BreakProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "type"> & {
  type?: string;
  class?: string;
  className?: string;
};

export const Break: Component<BreakProps> = (props) => {
  const [local, rest] = splitProps(props, ["type", "class", "className"]);
  const resolvedTagValue = () => mapOr(local.type, { "wbr": "wbr", "word": "wbr" }, "br");
  const cls = () => breakClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest} />
  );
};
