// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Badge shows a short status label.
 * Badge uses variant and size presets.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { badgeClasses, type BadgeSize, type BadgeVariant } from "./badge.shared";

/**
 * Badge renders label text in a div wrapper.
 */
export type BadgeProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "class" | "className" | "children" | "variant" | "size"> & {
  variant?: BadgeVariant;
  size?: BadgeSize;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Badge: Component<BadgeProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "class", "className", "children"]);
  const cls = () => badgeClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <div class={cls() || undefined} {...rest}>
      {local.children}
    </div>
  );
};
