// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Breadcrumb shows the current page location within a hierarchy.
 * Renders nav with ordered links and aria-current on the active item.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { breadcrumbClasses, type BreadcrumbItem } from "./breadcrumb.shared";
import { cn } from "../../utils";
import { isSetStr, orUndef } from "../../utils/expr";

/**
 * Breadcrumb renders the full navigation trail.
 */
export type BreadcrumbProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "items"> & {
  items?: BreadcrumbItem[];
  class?: string;
  className?: string;
};

export const Breadcrumb: Component<BreadcrumbProps> = (props) => {
  const [local, rest] = splitProps(props, ["items", "class", "className"]);
  const cls = () => breadcrumbClasses({ className: local.class ?? local.className });
  return (
    <nav class={cls() || undefined} {...rest}>
      <ol class="flex flex-wrap items-center gap-2">
        {(local.items ?? []).map((item, index) => (
          <li class="inline-flex items-center">
            {(isSetStr(item.href) && !(item.disabled)) ? (
              <a href={orUndef(item.href)} class={cn("text-sm", (item.current ? "font-medium" : (item.disabled ? "text-muted-foreground" : "text-primary underline-offset-4 hover:underline"))) || undefined} aria-current={item.current ? "page" : undefined}>
                {item.label}
              </a>
            ) : (
              <span class={cn("text-sm", (item.current ? "font-medium" : (item.disabled ? "text-muted-foreground" : "text-primary underline-offset-4 hover:underline"))) || undefined} aria-current={item.current ? "page" : undefined}>
                {item.label}
              </span>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
};
