// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Disclosure renders native details and summary elements.
 * Open is a static attribute only — no controlled-state contract.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { disclosureClasses, summaryClasses, type DisclosureSize, type DisclosureVariant, type SummarySize, type SummaryVariant } from "./disclosure.shared";

/**
 * Disclosure renders native details.
 */
export type DisclosureProps = Omit<JSX.DetailsHtmlAttributes<HTMLDetailsElement>, "class" | "className" | "children" | "variant" | "size" | "open"> & {
  variant?: DisclosureVariant;
  size?: DisclosureSize;
  open?: boolean;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Disclosure: Component<DisclosureProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "open", "class", "className", "children"]);
  const cls = () => disclosureClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <details class={cls() || undefined} open={local.open || undefined} {...rest}>
      {local.children}
    </details>
  );
};

/**
 * Summary renders native summary.
 */
export type SummaryProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "variant" | "size"> & {
  variant?: SummaryVariant;
  size?: SummarySize;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Summary: Component<SummaryProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "class", "className", "children"]);
  const cls = () => summaryClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <summary class={cls() || undefined} {...rest}>
      {local.children}
    </summary>
  );
};
