// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Image renders accessible img, picture, and source primitives.
 * Use Decorative for purely visual images so alt stays empty.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { imageClasses, pictureClasses, type ImageAspect, type ImageFit, type ImagePosition, type ImageSize, type ImageVariant } from "./image.shared";
import { oneOfOr } from "../../utils/expr";

/**
 * Image renders an accessible img element.
 */
export type ImageProps = Omit<JSX.ImgHTMLAttributes<HTMLImageElement>, "class" | "className" | "children" | "variant" | "size" | "alt" | "fit" | "position" | "aspect" | "loading" | "decoding" | "decorative"> & {
  variant?: ImageVariant;
  size?: ImageSize;
  alt?: string;
  fit?: ImageFit;
  position?: ImagePosition;
  aspect?: ImageAspect;
  loading?: string;
  decoding?: string;
  decorative?: boolean;
  class?: string;
  className?: string;
};

export const Image: Component<ImageProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "alt", "fit", "position", "aspect", "loading", "decoding", "decorative", "class", "className"]);
  const cls = () => imageClasses({ variant: local.variant, size: local.size, fit: local.fit, position: local.position, aspect: local.aspect, className: local.class ?? local.className });
  return (
    <img alt={((local.decorative ? "" : local.alt)) ?? ""} loading={oneOfOr(local.loading, "lazy", "eager")} decoding={oneOfOr(local.decoding, "async", "sync", "auto")} class={cls() || undefined} aria-hidden={local.decorative ? "true" : undefined} {...rest} />
  );
};

/**
 * Picture renders a responsive image wrapper.
 */
export type PictureProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Picture: Component<PictureProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className", "children"]);
  const cls = () => pictureClasses({ className: local.class ?? local.className });
  return (
    <picture class={cls() || undefined} {...rest}>
      {local.children}
    </picture>
  );
};

/**
 * Source renders a source candidate for picture, video, or audio.
 */
export type SourceProps = Omit<JSX.SourceHTMLAttributes<HTMLSourceElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
};

export const Source: Component<SourceProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className"]);
  return (
    <source {...rest} />
  );
};
