import contextActions from "../../internal/product/menus.json";
export const copy = {
  detailsLabel: "Details",
  contextActions,
  collapseFolders: "Collapse folders",
  quickOpen: "Find files (Ctrl+P)",
  noMatches: "No matching files in the explorer.",
  toggleExplorer: "Toggle explorer (Ctrl+B)",
  toggleAgent: "Toggle agent panel",
  markdownVisual: "Visual Markdown / MDX editor",
  markdownSource: "Markdown / MDX source",
  problems: "Problems",
  validateProject: "Check saved files",
  validating: "Checking saved files...",
  validationHelp: "Checks files on disk. Save your changes first. TypeScript requires local typescript and Node; Go requires the Go toolchain.",
  validationPassed: "Check passed",
  validationFailed: "Check failed",
  validationIdle: "No checks run yet.",
  validationPreview: "Project checks are available in the desktop app.",
  validationTool: "Validator",
  validationConfig: "TypeScript configuration",
  checkOptions: "Check options",
  findReplace: "Find / Replace (Ctrl+F)",
  findShort: "Find",
  goToLine: "Go to line (Ctrl+G)",
  newFile: "New file (Ctrl+N)",
  saveAll: "Save all",
  switchUnsaved: "This workspace has unsaved changes.",
  exitUnsaved: "Quit IDE BuildY with unsaved changes?",
  closeUnsaved: "This file has unsaved changes.",
  discardChanges: "Discard",
  saveAndContinue: "Save",
  cancelAction: "Cancel",
  spaces: "Tab size",
  position: "Ln / Col",
  utf8: "UTF-8",
  lineEndingLF: "LF",
  lineEndingCR: "CR",
  lineEndingCRLF: "CRLF",

  welcomeTitle: "Your workspace starts here",
  welcomeLead: "Open a local folder to edit files, use your terminal, and manage changes.",
  openFolder: "Open Folder",
  welcomeShortcut: "Ctrl+Shift+O to open a folder · Ctrl+, for settings",
  selectFile: "Select a file from the explorer to start editing.",
  sourceControl: "Source Control",
  refresh: "Refresh",
  changes: "Changes",
  staged: "Staged Changes",
  stage: "Stage file",
  unstage: "Unstage file",
  push: "Push commits",
  fetch: "Fetch",
  pull: "Pull",
  commit: "Commit staged changes",
  commitMessage: "Commit message",
  clean: "Working tree clean",
  gitUnavailable: "Open a Git repository to manage changes.",
  gitIdentity: "This IDE uses its own Git identity. Add user.name and user.email to data/home/.gitconfig beside the executable, then commit again.",
  gitAuth: "Git needs credentials. Sign in with the OS credential helper, then fetch or push again.",
  gitCommitNeedStage: "Stage files with +, then write a short message.",
  gitCommitNeedMessage: "Describe this commit, then commit the staged files.",
  gitStageAll: "Stage all",
  gitNoChanges: "No unstaged edits.",
  gitNoStaged: "Nothing staged yet.",
  gitInEditor: "Highlighted in the editor ·",
  terminal: "Terminal",
  newTerminal: "New terminal",
  closeTerminal: "Close terminal",
  terminalShell: "Terminal shell",
  terminalStart: "Start terminal",
  terminalEmpty: "Choose a shell and start a terminal in this workspace.",
  terminalExited: "Process exited. Open a new terminal to continue.",
  terminalUnavailable: "No supported shells found.",
  backEditor: "Back to workspace",
  saved: "Saved",
  unsaved: "Unsaved changes",
  save: "Save file",
  closeFile: "Close file",
  offlineAgent: "Agent offline",
  composerHint: "Enter to send · Shift+Enter for a new line",

  appTitle: "IDE BuildY",
  skipToContent: "Skip to editor",
  settingsTitle: "Settings",
  settingsHelp: "Personalize your workspace. Changes are saved automatically.",
  settingsOpen: "Open settings",
  settingsAppearance: "Appearance",
  settingsEditor: "Editor",
  settingsAgent: "Agent",
  settingsSecrets: "API keys stay in the host environment. They are not stored in the editor.",
  cancelLabel: "Close",
  themeAria: "Color theme",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  logoAlt: "BuildY",
  hideHeader: "Hide header",
  paletteAria: "Color palette",
  paletteDefault: "Default",
  paletteHinddy: "HinddY",
  editorTabSize: "Tab size",
  tabSize2: "2 spaces",
  tabSize4: "4 spaces",
  tabSize8: "8 spaces",
  editorFontScale: "Editor size",
  fontSmall: "Small",
  fontMedium: "Medium",
  fontLarge: "Large",
  editorLineWrap: "Wrap long lines (Alt+Z)",
  agentBridge: "Agent runtime",
  bridgeCursor: "Cursor (not connected)",
  bridgePi: "Pi (later)",
  bridgeOpenAi: "OpenAI SDK (later)",
  showThinking: "Show thinking",
  showToolTrace: "Show tool trace",
  statusReady: "Ready",
  statusLocalOnly: "Draft kept in the session. The sidecar is not connected.",
  statusSavedBuffer: "Saved.",
  statusSavedFile: "Saved",
  statusFileFailed: "Could not read that file.",
  statusWriteFailed: "Could not save that file.",
  retry: "Retry",
  showDetails: "Show details",
  saveAsAction: "Save As",
  faultMissing: "Missing file.",
  faultTooLarge: "File is larger than 1 MiB.",
  faultUtf8: "File is not UTF-8 text.",
  faultReadOnly: "File is read-only.",
  faultPermission: "Permission denied.",
  faultNoWorkspace: "No folder is open.",
  faultConflict: "The file changed on disk.",
  faultToolMissing: "Required tool is not installed.",
  faultCancelled: "Cancelled.",
  faultUnknown: "The operation failed.",
  faultSession: "Could not save the session. The window stayed open.",
  newFileInTree: "New file",
  newFolder: "New folder",
  gitAhead: "Ahead",
  gitBehind: "Behind",
  gitUpstream: "Upstream",
  gitKindConflict: "conflict",
  gitKindDeleted: "deleted",
  gitKindRenamed: "renamed",
  gitKindUntracked: "untracked",
  gitKindAdded: "added",
  gitKindModified: "modified",
  renameFile: "Rename",
  deleteFile: "Move to trash",
  restoreFile: "Restore last trash",
  copyPath: "Copy relative path",
  revealInOs: "Reveal in file manager",
  commandPalette: "Command palette",
  commandFind: "Find in file",
  commandLine: "Go to line",
  commandSave: "Save",
  commandSaveAs: "Save As",
  commandQuickOpen: "Find files",
  commandExplorer: "Toggle explorer",
  commandTerminal: "Toggle terminal",
  commandProblems: "Show problems",
  commandSettings: "Open settings",
  commandPaletteItem: "Command palette",
  commandEscape: "Close",
  searchInclude: "Include (node_modules, dist, .git when named)",
  searchExclude: "Exclude files",
  searchCancel: "Close search",
  navBack: "Go back",
  navForward: "Go forward",
  stopTask: "Stop task",
  taskExit: "Exit",
  cancelCheck: "Cancel check",
  simpleBrowser: "Simple Browser",
  browserAddress: "Address",
  browserGo: "Go",
  browserPick: "Pick element",
  browserPicking: "Click an element in the page",
  browserHardReload: "Hard reload (bypass cache)",
  browserPreview: "Simple Browser needs the desktop app. This Vite preview has no native WebView.",
  browserEmpty: "Enter an address and press Go.",
  browserDisconnected: "The browser tab disconnected. Press Go to reopen the page.",
  searchWorkspace: "Search in files",
  searchCase: "Match case",
  gitDiff: "Diff",
  formatChanged: "Document changed during formatting. Run Format Document again.",
  formatDocument: "Format document",
  goToDefinition: "Go to definition",
  languageUnavailable: "Language service unavailable",
  reopenClosed: "Reopen closed editor",
  uiZoom: "Interface zoom",
  zoom100: "100%",
  zoom125: "125%",
  zoom150: "150%",
  zoom200: "200%",
  runTask: "Run",
  testTask: "Test",
  taskCommand: "Command",
  languageReady: "Language ready",
  languageWorkspace: "Workspace symbols only",
  statusFileMissing: "This file is gone from disk. Use Save As to keep the buffer.",
  statusDiskChanged: "The file on disk changed. Save will ask before overwriting.",
  statusSaveConflict: "The file on disk changed since you opened it.",
  saveConflictOverwrite: "Overwrite the version on disk with this buffer?",
  saveConflictReload: "Reload the file from disk and discard your buffer?",
  hidePanel: "Hide panel",
  closeSession: "Close this terminal",
  validationStale: "This check is out of date. Save and run it again.",
  validationWrongTool: "Last check used a different tool. Run again to verify this one.",
  openFile: "Open File",
  welcomeNewFile: "New File",
  welcomeRecent: "Recent folders",
  welcomeRecentEmpty: "No recent folders yet.",
  recoverPrompt: "Restore unsaved buffers from the last session? Snapshots are written on each edit and again when the window closes.",
  recoverDiskChanged: "Restored buffers differ from the files now on disk. Save will ask before overwriting.",
  resetLayout: "Reset layout",
  statusFolderPrefix: "Agent root:",
  statusPreview: "Browser preview — in-memory workspace, no Go host.",
  previewChatUser: "Review the explorer, tabs, and editor chrome.",
  previewChatAssistant: "This tab is a Vite preview. Open files, stage git, and type in the terminal. Nothing writes to disk.",
  editorTitle: "Workspace",
  editorLead: "Open a folder from the File menu. That folder is the agent cwd.",
  workspaceNone: "No folder",
  workspaceOpenHint: "File → Open Folder",
  editorAria: "Workspace file editor",
  samplePath: "main.go",
  sampleDoc: "package main\n\nfunc main() {\n}\n",
  hintsTitle: "What this shell includes",
  hintsTrigger: "Show kit contract",
  hintsBody: "Native File menu opens the folder. Settings live there too. One Block per file.",
  treeTitle: "Files",
  treeEmpty: "Open a folder from File → Open Folder.",
  treeNoFiles: "No listable files in this folder.",
  treeLimited: "The explorer lists the first 4000 files. Use Quick Open or Search in files for the rest.",
  treeSkipped: "Hides node_modules, dist, and .git. Include those names in Search to scan them.",
  searchLimited: "Showing the first 200 matches. Narrow the query to see the rest.",
  searchEmpty: "No matches in listable text files.",
  saveAllCheck: "Save all and check",
  restartTask: "Restart",
  treeFolder: "Folder",
  treeFile: "File",
  treeDirOpen: "Open",
  treeDirClosed: "Closed",
  resizeTree: "Resize file tree",
  resizeChat: "Resize chat",
  chatTitle: "Agent",
  chatEmpty: "Plan your next change. Prompts stay in this session until an agent is connected.",
  composerLabel: "Prompt",
  composerPlaceholder: "Ask a question or describe a change…",
  sendLabel: "Send",
  stopLabel: "Stop",
  streamingLabel: "(streaming)",
  roleUser: "You",
  roleAssistant: "Assistant",
  roleThinking: "Thinking",
  roleTool: "Tool",
  longread: {
    toolbar: "Text formatting",
    paragraph: "Paragraph",
    heading2: "Heading 2",
    heading3: "Heading 3",
    bold: "Bold · Ctrl+B",
    italic: "Italic · Ctrl+I",
    strike: "Strikethrough",
    quote: "Quote",
    bulletList: "Bulleted list",
    orderedList: "Numbered list",
    codeBlock: "Code block",
    divider: "Divider",
    link: "Link",
    linkURL: "Link address",
    linkText: "Link text",
    removeLink: "Remove link",
    openLink: "Open link",
    invalidURL: "Enter a valid address: https://example.com/page",
    undo: "Undo · Ctrl+Z",
    redo: "Redo · Ctrl+Shift+Z",
    addBlock: "Block",
    blockHelp:
      "New line: / to choose a block · Ctrl+B bold · Ctrl+K link",
    commandSearch: "Find a block…",
    noCommands: "No matching block. Try another name.",
    close: "Close",
    cancel: "Cancel",
    apply: "Apply",
    imageHelp:
      "Paste an image URL. The caption is visible to readers; alt describes the image for accessibility. Local files are not uploaded.",
    editImage: "Edit image",
    removeImage: "Remove image",
    publicationHelp:
      "YAML front matter stays in the file. This IDE does not publish or upload.",
    searchPreview: "Link preview",
    emptyDescription: "Add a short description.",
    unsupported:
      "This document uses markup the block editor cannot keep (tables, tasks, raw HTML, or MDX JSX). Continue in source — the original text is kept.",
    openMarkdown: "Open source",
    outline: "Outline",
    emptyOutline: "Add headings and they will appear here.",
    duplicateBlock: "Duplicate",
    deleteBlock: "Delete block",
    seoHeading: "Front matter",
    description: "Description",
    slug: "Slug",
    canonical: "Canonical URL",
    ogTitle: "Social title",
    ogImage: "Social image URL",
    imageHeading: "Image",
    imageUrl: "Image URL",
    imageAlt: "Image description (alt)",
    imageTitle: "Image title",
    imageCaption: "Caption",
    imageCredit: "Credit / source",
    imageLayout: "Image width",
    layoutBox: "Compact",
    layoutContainer: "Text width",
    layoutFull: "Editor width",
    insertImage: "Insert image",
    updateImage: "Save image",
    moveBlockUp: "Move block up",
    moveBlockDown: "Move block down",
    dragBlock: "Current block",
    editorRegion: "Article text",
    placeholder: "Start writing or type / to choose a block…",
  },
};
