// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Dialog renders a native dialog root with an optional behavior hook.
 * The data-ui8kit hook defaults off; the registry ships no client JS.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { dialogClasses, type DialogSize, type DialogVariant } from "./dialog.shared";

/**
 * Dialog renders a native dialog element.
 */
export type DialogProps = Omit<JSX.DialogHtmlAttributes<HTMLDialogElement>, "class" | "className" | "children" | "variant" | "size" | "open"> & {
  variant?: DialogVariant;
  size?: DialogSize;
  open?: boolean;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Dialog: Component<DialogProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "open", "class", "className", "children"]);
  const cls = () => dialogClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <dialog class={cls() || undefined} open={local.open || undefined} {...rest}>
      {local.children}
    </dialog>
  );
};
